import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link' 
import Main from '../components/Main'
import Footer from '../components/Footer'

import { callApi } from '../functions/functions'

export default function Home({ movies, error }) {
  console.log(movies)
  return (
    <div className="">
      <Head>
        <title>MovieEra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
          integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
          crossOrigin="anonymous"
        />
      </Head>
      <Link href="/movies">
      <a>Movies</a>
      </Link>

      {movies && movies.map((movie, i) => {
        return (<h1 className="font-semibold text-purple-700" key={i}>{movie.original_title}</h1>)
      })}

      {error && <h1 className="text-red-400">{error}</h1>}
      <Main />
      <Footer />

    </div>
  )
}

export async function getStaticProps() {

  const revalidate = parseInt(86400 / 4)

  const [movies, error] = await callApi("http://localhost:3000/api/trending")


  return {
    props: { movies, error },
    revalidate
  }
}